baseURL: "https://nutchi.net"
title: 君の牛丼を食べたい
languageCode: ja-jp
theme: PaperMod
enableRobotsTXT: true

params:
  description: 色々やったことの備忘録。ポエムはたぶん書きません。
  keywords: [ blog ]
  ShowReadingTime: true
  ShowRssButtonInSectionTermList: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: 君の牛丼を食べたい
    Content: 色々やったことの備忘録。ポエムはたぶん書きません。

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
